spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/eq21
    username: eq21
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    br.ufpb.dsc.mercado: INFO

aws:
  s3:
    endpoint: http://minio:9000
    public-endpoint: http://localhost:9000